export default data = [
    {
        id: 1,
        name: "Alex",
        lastname: "Black",
        middlename: "",
        parentsId: [2, 3],
        male: true,
    },
    {
        id: 2,
        name: "John",
        lastname: "Black",
        middlename: "Alex",
        parentsId: [1],
        male: true,
    },
    {
        id: 3,
        name: "Jane",
        lastname: "Black",
        middlename: "Alex",
        parentsId: [1],
        male: false,
    },
    {
        id: 4,
        name: "Sergey",
        lastname: "Borovich",
        middlename: "",
        parentsId: [],
        male: true,
    },
    {
        id: 5,
        name: "Emily",
        lastname: "Borovich",
        middlename: "Sergey",
        parentsId: [3, 4],
        male: false,
    },
    {
        id: 5,
        name: "Michael",
        lastname: "Black",
        middlename: "Alex",
        parentsId: [2],
        male: true,
    },
];
